#!/bin/bash

# Init script for the releasedata sinatra webapp

# chkconfig: - 80 05
# description: Enable sinatra Release Data web service

### BEGIN INIT INFO
# Provides:          releasedata
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description:       Release Data sinatra app
# Short-Description: Enable sinatra web service providing Release Data
### END INIT INFO


